image: node:10

cache:
  key: node_modules
  paths:
    - node_modules/

stages:
  - lint
  - test
  - build

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - echo "No tests to run"

build:
  stage: build
  script:
    - npm run build
    - mv web-ext-artifacts/tab_center_reborn-*.zip extension.zip
  artifacts:
    paths:
      - extension.zip
    expire_in: 1 month
